function measuredMetabolites = inputMeasuredMetabolites_ECOLI113C()
% inputSimulateMetabolites - define metabolites to be simulated
% in the following format: 
% 'FragmentName: MetaboliteName @ carbon indeces'
% For example, pyruvate: 'PYR13: PYR @ 1 2 3';...
% For example, pyruvate fragment 'PYR12: PYR @ 1 2';...
% NOTE: MetaboliteName has to be the same as in the provided stoichiometric model

measuredMetabolites = {...
            'BPG13';... 
            'BPG23';...
            'BPG12';...
            'PYR13';...
            'PYR23';...
            'OAA12';...
            'PEP12';...
            };
end