function measuredMetabolites = inputMeasuredMetabolites()
% inputSimulateMetabolites - define metabolites to be simulated
% in the following format: 
% 'FragmentName: MetaboliteName @ carbon indeces'
% For example, pyruvate: 'PYR13: PYR @ 1 2 3';...
% For example, pyruvate fragment 'PYR12: PYR @ 1 2';...
% NOTE: MetaboliteName has to be the same as in the provided stoichiometric model

measuredMetabolites = {...
            'OGA15';...
            'OGA25';...
            'OGA12';...
            'PEP13';...
            'PEP23';...
            'PEP12';...
            'E4P14';...
            'BPG13';... 
            'BPG23';...
            'BPG12';...
            'PYR13';...
            'PYR23';...
            'PYR12';...
            'OAA14';... 
            'OAA24';...
            'OAA12';...
            };
end