function list = inputRatios()
% inputRatios - SUMOFLUX defined list of ratios
% Add custom ratios in the following format: 
% Syntax: 
% {'Ratio name'}{coef 'flux_name' 'flux_type'}{coef 'flux_name' 'flux_type'}
%               ---------nominator---------- / -------denominator---------
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
list = {...
   {'Glycolysis/PPP'} {1 'pgi' 'net'} {1 'pgi' 'net' 1 'zwf' 'net' };...
   {'Pyruvate from ED'} {1 'edp2' 'net'} {1 'edp2' 'net' 1 'pyk' 'net' 1 'mae' 'net'};...
   {'gluconeogenesis (PEP from oxaloacetate)' } {1 'pck' 'net' } {1 'pck' 'net' 1 'eno' 'net'};...
   {'Pyruvate from malic enzyme'} {1 'mae' 'net' } {1 'mae' 'net'  1 'pyk' 'net' 1 'edp2' 'net'};...
   {'BSUB Pyruvate from malic enzyme'} {1 'mae' 'net' } {1 'mae' 'net'  1 'pyk' 'net'};...
   {'anaplerosis (OAA from pyruvate)'} {1 'pyc' 'net' } {1 'pyc' 'net'  1 'sdh' 'net' 1 'gs1' 'net'};...
   {'BSUB anaplerosis (OAA from pyruvate)'} {1 'pyc' 'net' } {1 'pyc' 'net'  1 'mdh' 'net'};...
   {'Oxaloacetate from TCA' } {1 'sdh' 'net' } {1 'pyc' 'net' 1 'sdh' 'net' 1 'gs1' 'net'};...
   {'Oxaloacetate from glyoxylate shunt' } {1 'gs1' 'net'} {1 'sdh' 'net' 1 'gs1' 'net' 1 'pyc' 'net'};...
   };
