function measuredMetabolites = inputMeasuredMetabolites_ECOLI20U13C()
% inputSimulateMetabolites - define metabolites to be simulated
% in the following format: 
% 'FragmentName: MetaboliteName @ carbon indeces'
% For example, pyruvate: 'PYR13: PYR @ 1 2 3';...
% For example, pyruvate fragment 'PYR12: PYR @ 1 2';...
% NOTE: MetaboliteName has to be the same as in the provided stoichiometric model

measuredMetabolites = {...
            'OAA14';... 
            'OAA24';...
            'OGA25';...
            'PEP13';...
            'PEP23';...
            'PEP12';...
            'PYR13';...
            'PYR23';...
            'BPG13';... 
            };
end