function simulateMetabolites = inputSimulateMetabolites()
% inputSimulateMetabolites - define metabolites to be simulated
% in the following format: 
% 'FragmentName: MetaboliteName @ carbon indeces'
% For example, pyruvate: 'PYR13: PYR @ 1 2 3';...
% For example, pyruvate fragment 'PYR12: PYR @ 1 2';...
% NOTE: MetaboliteName has to be the same as in the provided stoichiometric model

simulateMetabolites = {...
            'OGA15: OGA @ 1 2 3 4 5';...
            'OGA25: OGA @ 2 3 4 5';...
            'OGA12: OGA @ 1 2';...
            'PEP13: PEP @ 1 2 3';...
            'PEP23: PEP @ 2 3';...
            'PEP12: PEP @ 1 2';...
            'E4P14: E4P @ 1 2 3 4';...
            'BPG13: BPG @ 1 2 3';... 
            'BPG23: BPG @ 2 3';...
            'BPG12: BPG @ 1 2';...
            'PYR13: PYR @ 1 2 3';...
            'PYR23: PYR @ 2 3';...
            'PYR12: PYR @ 1 2';...
            'OAA14: OAA @ 1 2 3 4';... 
            'OAA24: OAA @ 2 3 4';...
            'OAA12: OAA @ 1 2';...
            'AcCoA12: AcCoA @ 1 2';...
            'AcCoA2: AcCoA @ 2';...
            'P5P15: P5P @ 1 2 3 4 5';...
            'P5P25: P5P @ 2 3 4 5';...
            'P5P12: P5P @ 1 2';...
            };
end
